### ISSUE TITLE
Pint decorators incomplete

### ISSUE THREAD

**Issue by zoeith** [manoharan-lab/structural-color#102]
Pint doesn't seem to have a native way of handling function signatures with default params. Every parameter needs to be specified in the `check` decorators.

In the tutorial, this fails:
`import structcol.refractive_index as ri`

```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-626ca02fc738> in <module>
----> 1 import structcol.refractive_index as ri

~/Documents/Results/ClarkeCeramicsOptics/codebase/structural-color/structcol/refractive_index.py in <module>
    154 
    155 @ureg.check(None, '[length]')   # ensures wavelen has units of length
--> 156 def n(material, wavelen, index_data=None, wavelength_data=None, kind='linear'):
    157     """
    158     Refractive index of various materials.

~/opt/anaconda3/envs/scatter/lib/python3.7/site-packages/pint/registry_helpers.py in decorator(func)
    327             raise TypeError(
    328                 "%s takes %i parameters, but %i dimensions were passed"
--> 329                 % (func.__name__, count_params, len(dimensions))
    330             )
    331 

TypeError: n takes 5 parameters, but 2 dimensions were passed
```
Also see: https://github.com/hgrecco/pint/issues/1065

Relatedly, it seems there's some ambiguity between function signature defaults and doc strings regarding units of angles (deg[rees] or dimensionless). https://github.com/manoharan-lab/structural-color/blob/master/structcol/model.py#L49

**Comment by zoeith** [comment]
Updated on my fork by removing decorators (and likewise in python-mie).  Tutorial runs fine now though with many `UnitStrippedWarning`s.

**Comment by AnnieStephenson** [comment]
updated for new Pint
