### ISSUE TITLE
Implement multilayer Mie solution

### ISSUE THREAD

**Issue by vnmanoharan** [manoharan-lab/structural-color#2]
Implement multilayer Mie solution using version from holopy (holopy/scattering/theory/mie_f/multilayer_sphere_lib.py). Also need to modify calc_cross_sections and calc_ang_scat to be able to handle multilayer as well as homogeneous spheres. (multilayer solution is necessary for modeling core-shell particles).

**Comment by vnmanoharan** [comment]
@victoriahwang89, is multilayer now merged into pymie and available in structcol?

**Comment by victoriahwang89** [comment]
@vnmanoharan, yes, multilayer is merged into pymie and available in structcol.

**Comment by vnmanoharan** [comment]
Then can we close this issue?  Unless `calc_cross_sections` and `calc_ang_scat` have not yet been modified to handle multilayer.

**Comment by victoriahwang89** [comment]
Yes, we can close the issue. calc_cross_sections, calc_ang_scat, and all other relevant functions have been modified to include the option of multilayered particles.
