### ISSUE TITLE
Pint implementation is slow

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/structural-color#28]
I ran some profiling to see where the infer_structcol package is losing time. It looks like the calc_reflection function in montecarlo.py is now very fast after vectorizing (runs in .003 s per call!). The scatter function takes 97% of total run time, which includes the inference and emcee overhead.

About 75% of the code run time is spent running pint functions, not including subcalls to numpy or internal python functions. Switching from pint quantities to numpy arrays would presumably cut run time by a factor of 4. Obviously this is not desirable, since there's a reason pint is used in the first place, but maybe there are smarter ways to handle pint calls and manipulation.

![screenshot from 2017-04-25 09 32 39](https://cloud.githubusercontent.com/assets/19350183/25387990/8b64df06-299a-11e7-958d-f4ed8f737aa2.png)

**Comment by barkls** [comment]
Fixed in #29. It turns out much more than 75% of the time was spent doing Pint conversions, since we get a 35x speed up!

**Comment by vnmanoharan** [comment]
@barkls : can't see the profiling results (image seems to be corrupted), but would be interested to see them, if you can run them again using the patched version of structcol.
