### ISSUE TITLE
Make scattering calculations work with complex indices of refraction

### ISSUE THREAD

**Issue by vnmanoharan** [manoharan-lab/structural-color#32]
Should test the Mie scattering calculations with complex indices, make sure the functions in refractive_index.py can return complex indices, and make sure that the single-scattering model and MC return reasonable results for complex indices.

**Comment by vnmanoharan** [comment]
@victoriahwang89: is this issue addressed in the latest version?

**Comment by victoriahwang89** [comment]
@vnmanoharan: complex indices are tested in pymie, the single-scattering model and MC. Added a test to test_refractive_index.py for complex indices.
