### ISSUE TITLE
Transport length calculation missing

### ISSUE THREAD

**Issue by vnmanoharan** [manoharan-lab/structural-color#4]
Should be added to output of model.reflection().

**Comment by vnmanoharan** [comment]
fixed now, but still needs unit tests to make sure it is being calculated correctly.

**Comment by vnmanoharan** [comment]
@AnnieStephenson, @victoriahwang89 can this issue be closed?

**Comment by AnnieStephenson** [comment]
Transport length calculations and tests have been implemented. The current transport length tests check whether the transport length for various features (core-shell, absorption, polydispersity) approaches the transport length without these features when the shell/absorption/polydispersity is very small. Is this sufficient?

**Comment by vnmanoharan** [comment]
We probably need a test on the value of the transport length for a dilute system (where the structure factor is unity).  In that case, the transport length can be calculated from the Mie results for the asymmetry factor and the scattering cross-section.

**Comment by victoriahwang89** [comment]
Added a test to make sure the transport length for a dilute system calculated with the single scattering model is the same as the transport length calculated with the asymmetry factor and scattering cross section from Mie theory.
