### ISSUE TITLE
Replace fsolve with Newton's method in find_exit_intersect()

### ISSUE THREAD

**Issue by AnnieStephenson** [manoharan-lab/structural-color#48]
Should remove fsolve and np.vectorize() for solving for intersection of trajectory and sphere boundary, and replace with [Newton's method](https://stackoverflow.com/questions/39725419/solving-sets-of-non-linear-equations-as-an-array?rq=1). This could improve performance by a factor of 1000.

**Comment by vnmanoharan** [comment]
@AnnieStephenson: is this implemented in the latest version?

**Comment by AnnieStephenson** [comment]
I ended up implementing the [analytical solution](http://www.ambrsoft.com/TrigoCalc/Sphere/SpherLineIntersection_.htm) for the intersection of the exit vector and the sphere boundary instead. This avoids iterative solvers altogether.
