### ISSUE TITLE
sample_step() uses extinction coefficient

### ISSUE THREAD

**Issue by victoriahwang89** [manoharan-lab/structural-color#51]
The sample_step() function currently uses the extinction coefficient (scattering + absorption), but we already have Beer-Lambert that accounts for absorption in the absorb() function. Might be okay to keep it this way if we think that on average the step sizes will indeed be smaller when there is absorption, so sample_step() should use the extinction coefficient. But we should keep this issue in mind in case future results overestimate absorption.

**Comment by vnmanoharan** [comment]
@victoriahwang89 did we change the code to use the scattering length instead?

**Comment by victoriahwang89** [comment]
@vnmanoharan, yes, the latest merge includes the update of using the scattering length instead of the extinction length for sample_step(). This issue should be closed now.
